CattleMgm/ViewModels/Milk/MilkViewModel.cs
namespace CattleMgm.ViewModels.Milk
{
    public class MilkViewModel
    {
        public int CattleId { get; set; }

        public int Id { get; set; }
        public string Identifier { get; set; }
       
        public string CattleName { get; set; }

        public double LitersCollected { get; set; }

        public string DateCollected { get; set; }

        public double Price { get; set; }

        public double TotalProfit { get; set; }

    }

    public class MilkCreateViewModel
    {
        public int CattleId { get; set; }
        public double Price { get; set; }

        public double LitersCollected { get; set; }

        public string? Identifier { get; set; }
    }
    public class MilkEditViewModel :MilkCreateViewModel
    {
       public int Id { get; set; }


    }
}

CattleMgm/Controllers/MilkController.cs
using CattleMgm.Data.Entities;
using CattleMgm.Data;
using CattleMgm.Models;
using CattleMgm.Repository.Media;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CattleMgm.ViewModels.Milk;
using CattleMgm.Repository.Cattles;
using Microsoft.AspNetCore.Mvc.Rendering;
using CattleMgm.Helpers.Security;
using CattleMgm.ViewModels.Menu;
using CattleMgm.ViewModels;
using CattleMgm.ViewModels.Submenu;
using CattleMgm.Repository.Milk;

namespace CattleMgm.Controllers
{
    public class MilkController : BaseController
    {
        public IMilkRepository _MilkRepository;
        public ICattleRepository _CattleRepository;
        public MilkController(ApplicationDbContext context
            , praktikadbContext db
            , UserManager<ApplicationUser> userManager
            , IMilkRepository milkRepository) : base(context, db, userManager)
        {
            _MilkRepository = milkRepository;
        }
        public async Task<IActionResult> Index()
        {
            var milk = new List<CattleMilk>();
            
            milk= await _MilkRepository.GetAllMilk();

            List<MilkViewModel> model = new List<MilkViewModel>();

            foreach (var item in milk)
            {
                model.Add(new MilkViewModel
                {
                    Id = item.Id,
                    CattleName = item.Cattle.Name,
                    Identifier = item.Cattle.UniqueIdentifier.ToString(),
                    DateCollected = item.Created.ToString("dd/MM/yyyy HH:mm"),
                    LitersCollected = item.LitersCollected,
                    Price = item.Price,
                    TotalProfit = item.Price * item.LitersCollected
                }) ;
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var cattles = await _db.Cattle.Select(q => new { q.Id, Name = q.Name }).ToListAsync();
            var farmerId = await _db.Farmer.Where(x => x.UserId == user.Id).FirstOrDefaultAsync();
            //if (!User.IsInRole("Administrator"))
            //{
            //    cattles = _CattleRepository.GetCattlesByFarmerId(farmerId.Id);
            //}
            //else
            //{
            //    cattles = _CattleRepository.GetCattles();
            //}
            ViewBag.Cattles = new SelectList(cattles, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(MilkCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Ka ndodhur nje gabim. Plotesoni te dhenat obligative");
                return View(model);
            }

            CattleMilk cattleMilk = new CattleMilk();
            cattleMilk.Identifier = Guid.NewGuid();
            cattleMilk.LitersCollected = model.LitersCollected;
            cattleMilk.Price = model.Price;
            cattleMilk.Created = DateTime.Now;
            cattleMilk.CreatedBy = user.Id;
            cattleMilk.CattleId = model.CattleId;

            await _db.CattleMilk.AddAsync(cattleMilk);

            await _db.SaveChangesAsync();

            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult _Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            //int did = AesCrypto.Decrypt<int>(ide);

            var milk = _db.CattleMilk.Find(id);


            if (milk == null)
            {
                return NotFound();
            }

            MilkEditViewModel editViewModel = new MilkEditViewModel
            {
                Id = milk.Id,
                CattleId = milk.CattleId,
                Price = milk.Price,
                LitersCollected = milk.LitersCollected

            };

            return PartialView(editViewModel);
        }

        [HttpPost]
        public IActionResult _Edit(MilkEditViewModel model)
        {
            ErrorViewModel error = new ErrorViewModel { ErrorNumber = Helpers.ErrorStatus.Success, ErrorDescription = "Milk forma eshte modifikuar me sukses", Title = "Sukses" };

            if (!ModelState.IsValid)
            {
                error = new ErrorViewModel { ErrorNumber = Helpers.ErrorStatus.Warning, ErrorDescription = "Plotesoni te dhenat obligative", Title = "Lajmerim" };
                return Json(error);
            }
            var milk = _db.CattleMilk.Find(model.Id);

            if (milk == null)
            {
                return NotFound();

            }
            milk.Id = model.Id;
            milk.Price = model.Price;
            milk.LitersCollected = model.LitersCollected;

            _db.Update(milk);

            _db.SaveChanges();

            return Json(error);

        }
        [HttpPost]
        public async Task<IActionResult> Delete(int Id)
        {

            if (Id == null)
            {
                return BadRequest();
            }


            var milk = _db.CattleMilk.Find(Id);
            if (milk != null)
            {
                var result = _db.CattleMilk.Remove(milk);

                await _db.SaveChangesAsync();

            }

            return Json("success");

        }
    }
}

CattleMgm/Views/Milk/Create.cshtml
@model MilkCreateViewModel
@{
    ViewData["Title"] = "Regjistrimi i mbledhjes se qumeshtit";
}

<div class="card">
    <div class="card-header with-border">
        <h4>Plotesoni te dhenat me poshte</h4>
    </div>
    <form id="createForm" method="post">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <label class="required" asp-for="CattleId">Gjedhja</label>
                    @Html.DropDownListFor(m=>m.CattleId, ViewBag.Cattles as SelectList, "Zgjedh", new { @class = "form-control select2"})
                    @*ekuivalente me dropdownlistfor*@
                    @* <select asp-for="RoleId" asp-items="ViewBag.Roles" class="form-control select2">
                    <option></option>
                    </select>*@
                    <span asp-validation-for="CattleId" class="text-danger"></span>
                </div>
                <div class="col-md-4">
                    <label asp-for="LitersCollected">Litrat e mbledhura</label>
                    <input asp-for="LitersCollected" class="form-control" />
                    <span asp-validation-for="LitersCollected" class="text-danger"></span>
                </div>
                <div class="col-md-4">
                    <label asp-for="Price">Qmimi</label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>


            </div>
        </div>
        <div class="card-footer">
            <input type="submit" class="btn btn-sm btn-primary" value="Regjistro" />
        </div>
    </form>

</div>

CattleMgm/Views/Milk/Edit.cshtml
@model MilkEditViewModel
@{
    int i = 1;
}

<div class="modal-header">
    <h5 class="modal-title">Editimi i formes se qumeshtit</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <form asp-action="Edit" asp-controller="Milk" class="noLoading" id="frmEditMilk" method="post" data-ajax="true" data-ajax-method="post" data-ajax-success="EditSuccess" role="form">

        @Html.AntiForgeryToken()
        <input asp-for="Id" hidden />
        <div class="row form-group">
            <div class="col-md-4">
                <label asp-for="CattleId" class="required form-label"></label>
                <input asp-for="CattleId" class="form-control" />
                <span asp-validation-for="CattleId" class="text-danger" />
            </div>
            <div class="col-md-4">
                <label asp-for="LitersCollected" class="required form-label"></label>
                <input asp-for="LitersCollected" class="form-control" />
                <span asp-validation-for="LitersCollected" class="text-danger" />
            </div>
            <div class="col-md-4">
                <label asp-for="Price" class="required form-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger" />
            </div>
        </div>
        <div class="modal-footer modal-footer-uniform w-full justify-content-between">
            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Mbyll</button>
            <button type="submit" class="btn btn-outline-primary">Ndrysho</button>
        </div>
    </form>


</div>

<script type="text/javascript">
    var form = $('#frmEditMilk');
    form.removeData('validator');
    form.removeData('unobtrusiveValidation');
    $.validator.unobtrusive.parse(form);

    function EditSuccess(data) {
        console.log(data);

        if (data.errorNumber == ErrorNumber.SUCCESS) {
            Swal.fire({
                icon: 'success',
                title: data.title,
                text: 'Rekordi u ndryshua me sukses',
                confirmButtonText: "Okay"
            }).then(t => {
                window.location.reload()
            })
        } else if (data.errorNumber == ErrorNumber.WARNING) {
            Swal.fire({
                icon: 'warning',
                title: data.title,
                text: data.ErrorDescription,
                confirmButtonText: "Okay"
            })
        }
    }
</script>

CattleMgm/Views/Milk/Index.cshtml
@model List<MilkViewModel>

@{
    ViewData["Title"] = "Lista e mbledhjes se qumeshtit";
}
<div class="card">
    <div class="card-header">
        <div class="card-toolbar float-end">
            <a class="btn btn-sm btn-primary" asp-action="Create" asp-controller="Milk">Regjistro</a>
        </div>
    </div>
    <div class="card-body">
        <div class="button-items" style="float:right;">
            <div class="btn-group dropstart">
                <button style="margin:0 5px 7px 0" type="button" class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="mdi mdi-chevron-left"></i>Shkarko
                </button>
                <div class="dropdown-menu">
                    <button class="dropdown-item" onclick="Report(ReportType.PDF)">
                        <img src="~/Media/Extensions/pdf.png" class="btn-download" asp-append-version="true" />
                        <span class="title text-center w-100">PDF</span>
                    </button>
                    <button class="dropdown-item" onclick="Report(ReportType.EXCEL)">
                        <img src="~/Media/Extensions/xls.png" class="btn-download" asp-append-version="true" />
                        <span class="title text-center w-100">Excel</span>
                    </button>
                </div>
            </div>
        </div>
        <table id="milk-table" class="table table-responsive">
            <thead>
                <tr>
                    <th>Identifikuesi </th>
                    <th>Emri i gjedhes</th>
                    <th>Data e grumbullimit</th>
                    <th>Litrat te mbledhura</th>
                    <th>Cmimi</th>
                    <th>Profiti</th>
                    <th>Veprimet</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Identifier</td>
                        <td>@item.CattleName</td>
                        <td>@item.DateCollected</td>
                        <td>@item.LitersCollected l</td>
                        <td>@item.Price $</td>
                        <td>@item.TotalProfit $</td>
                        <td class="button-td">
                            <a class="btn btn-sm btn-primary" onclick="EditMilk(@item.Id)"><i class="fa fa-edit"></i>Edit</a>
                            <a class="btn btn-sm btn-danger" href="javascript:;" onclick="DeleteMilk('@item.Id')">Delete</a>
                            @*@(await Html.PartialAsync("_ActionButtonsPartial", new List<ActionButton> { new ActionButton { Title = Resource.Edit, Icon = SvgIcon.Edit, OnClick = $"EditSubMenu('{menu.mide}', '{AesCrypto.Enkrypt(menu.ide) }')", Display = true },
                        new ActionButton{ Title = Resource.Delete, Icon = SvgIcon.Delete, OnClick = $"DeleteSubMenu('{AesCrypto.Enkrypt(menu.ide) }')", Display = true }, }))
                        *@
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $("#milk-table").DataTable({
            keys: true,
            responsive: true,
            pageLength: 10,
            "ordering": false

        });
        function EditMilk(Id) {
            $('#modal-center-large').find('.modal-content').load('@Url.Action("_Edit", "Milk")?id=' + Id, function () {
                $('#modal-center-large').modal('toggle')
            })
        }
        function DeleteMilk(Id) {
            debugger;
            Swal.fire({
                title: 'A jeni të sigurt?',
                text: "Ju nuk do mund të ktheheni prapa!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Fshij'
            }).then((result) => {
                debugger;
                if (result.value) {
                    $.ajax({
                        url: '@Url.Action("Delete", "Milk")/' + Id,
                        type: 'POST',
                        success: function (result) {
                            Swal.fire({
                                title: 'Fshier!',
                                text: 'E dhena u fshi me sukses!',
                                icon: 'success',
                                timer: 1500,
                                timerProgressBar: true,
                            }).then((result) => {
                                location.reload();
                            });
                        },
                        error: function (xhr, status, error) {
                            Swal.fire({
                                title: 'Error!',
                                text: 'An error occurred while deleting the role: ' + error,
                                icon: 'error'
                            });
                        }
                    });
                }
            });
        }
        function Report(type) {
            if (type == '@((int)ReportType.PDF)' || type == '@((int)ReportType.Excel)') {
                $.ajax({
                    url: "/Milk/OpenIndexReport",
                    cache: false,
                    type: "POST",
                    dataType: "json",
                    success: function () {
                        if (type == '@((int)ReportType.Excel)')
                            window.open("/Reports/Design/?format=excel", '_blank');
                        else {
                            let W = window.open("/Reports/Design/?format=pdf", '_blank');
                            W.onload = function () { this.document.title = 'Raporti'; }
                        }
                    }
                });
            }
        }
    </script>

}

CattleMgm/Views/Milk/_Edit.cshtml
@model MilkEditViewModel
@{
    int i = 1;
}

<div class="modal-header">
    <h5 class="modal-title">Editimi i formes se qumeshtit</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <form asp-action="_Edit" asp-controller="Milk" class="noLoading" id="frmEditMilk" method="post" data-ajax="true" data-ajax-method="post" data-ajax-success="EditSuccess" role="form">

        @Html.AntiForgeryToken()
        <input asp-for="Id" hidden />
        <div class="row form-group">
            <div class="col-md-4">
                <label asp-for="CattleId" class="required form-label"></label>
                <input asp-for="CattleId" class="form-control" />
                <span asp-validation-for="CattleId" class="text-danger" />
            </div>
            <div class="col-md-4">
                <label asp-for="LitersCollected" class="required form-label"></label>
                <input asp-for="LitersCollected" class="form-control" />
                <span asp-validation-for="LitersCollected" class="text-danger" />
            </div>
            <div class="col-md-4">
                <label asp-for="Price" class="required form-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger" />
            </div>
        </div>
        <div class="modal-footer modal-footer-uniform w-full justify-content-between">
            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Mbyll</button>
            <button type="submit" class="btn btn-outline-primary">Ndrysho</button>
        </div>
    </form>


</div>

<script type="text/javascript">
    var form = $('#frmEditMilk');
    form.removeData('validator');
    form.removeData('unobtrusiveValidation');
    $.validator.unobtrusive.parse(form);

    function EditSuccess(data) {
        console.log(data);

        if (data.errorNumber == ErrorNumber.SUCCESS) {
            Swal.fire({
                icon: 'success',
                title: data.title,
                text: 'Rekordi u ndryshua me sukses',
                confirmButtonText: "Okay"
            }).then(t => {
                window.location.reload()
            })
        } else if (data.errorNumber == ErrorNumber.WARNING) {
            Swal.fire({
                icon: 'warning',
                title: data.title,
                text: data.ErrorDescription,
                confirmButtonText: "Okay"
            })
        }
    }
</script>