CattleMgm/ViewModels/Breed/BreedViewModel.cs
using Microsoft.Build.Framework;

namespace CattleMgm.ViewModels.Breed
{
    public class BreedViewModel
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public int? Type { get; set; }
    }
    public class BreedCreateViewModel
    {

        [Required]
        public string Name { get; set; }

        public int? Type { get; set; }
    }
    public class BreedEditViewModel :BreedCreateViewModel
    {
        public int Id { get; set; }
    }

}

CattleMgm/Controllers/BreedController.cs
using CattleMgm.Data;
using CattleMgm.Data.Entities;
using CattleMgm.Helpers.Security;
using CattleMgm.Models;
using CattleMgm.Models.Session;
using CattleMgm.Repository.Cattles;
using CattleMgm.ViewModels;
using CattleMgm.ViewModels.Breed;
using CattleMgm.ViewModels.User;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace CattleMgm.Controllers
{
    public class BreedController : BaseController
    {
        public ICattleRepository _cattleRepository;
        public BreedController(ApplicationDbContext context
            , praktikadbContext db
            , UserManager<ApplicationUser> userManager
            , ICattleRepository cattleRepository
            ) : base(context, db, userManager)
        {
            _cattleRepository = cattleRepository;
        }
        public IActionResult Index()
        {
            
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateAsync(BreedCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Ka ndodhur nje gabim. Plotesoni te dhenat obligative");
                return View(model);
            }
            var existingBreed = await _db.Breed.FirstOrDefaultAsync(b => b.Name == model.Name || b.Type == model.Type);

            if (existingBreed != null)
            {
                if (existingBreed.Name == model.Name && existingBreed.Type == model.Type)
                {
                    ModelState.AddModelError("", "Nje kafshe me kete emer dhe tip ekziston tashme");
                }
                else if (existingBreed.Name == model.Name)
                {
                    ModelState.AddModelError("", "Nje kafshe me kete emer ekziston tashme");
                }
                else
                {
                    ModelState.AddModelError("", "Nje kafshe me kete tip ekziston tashme");
                }

                return View(model);
            }

            Breed breed = new Breed();

            breed.Name = model.Name;
            breed.Type = model.Type;
            breed.Created = DateTime.Now;
            breed.CreatedBy = user.Id;

            await _db.Breed.AddAsync(breed);
            await _db.SaveChangesAsync();


            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Edit(string? ide)
        {

            if (ide == null)
            {
                return BadRequest();
            }

            int did = AesCrypto.Decrypt<int>(ide);

            var breed = _db.Breed.Find(did);

            if (breed == null)
            {
                return NotFound();
            }

            BreedEditViewModel editViewModel = new BreedEditViewModel
            {
                Id = did,
                Name = breed.Name,
               Type =breed.Type
            };

            return PartialView(editViewModel);
        }

        [HttpPost]
        public IActionResult Edit(BreedEditViewModel model)
        {

            ErrorViewModel error = new ErrorViewModel { ErrorNumber = Helpers.ErrorStatus.Success, ErrorDescription = "Breed eshte modifikuar me sukses", Title = "Sukses" };

            if (!ModelState.IsValid)
            {
                error = new ErrorViewModel { ErrorNumber = Helpers.ErrorStatus.Warning, ErrorDescription = "Plotesoni te dhenat obligative", Title = "Lajmerim" };
                return Json(error);
            }

            var breed = _db.Breed.Find(model.Id);

            if (breed == null)
            {
                return NotFound();
            }
            var existingBreed = _db.Breed.FirstOrDefault(b => b.Id != model.Id && (b.Name == model.Name || b.Type == model.Type));

            if (existingBreed != null)
            {
                if (existingBreed.Name == model.Name && existingBreed.Type == model.Type)
                {
                    ModelState.AddModelError("", "Nje kafshe me kete emer dhe tip ekziston tashme");
                }
                else if (existingBreed.Name == model.Name)
                {
                    ModelState.AddModelError("", "Nje kafshe me kete emer ekziston tashme");
                }
                else
                {
                    ModelState.AddModelError("", "Nje kafshe me kete tip ekziston tashme");
                }

                error = new ErrorViewModel { ErrorNumber = Helpers.ErrorStatus.Warning, ErrorDescription = "Nje kafshe me kete emer ose tip ekziston tashme", Title = "Lajmerim" };
                return Json(error);
            }


            breed.Name = model.Name;
            breed.Type = model.Type;
            breed.LastUpdated = DateTime.Now;
            breed.LastUpdatedBy = user.Id;



            _db.Update(breed);

            _db.SaveChanges();

            return Json(error);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var did = AesCrypto.Decrypt<int>(id);
            if (id == null)
            {
                return BadRequest();
            }


            var breed = _db.Breed.Find(did);
            if (breed != null)
            {
                var result = _db.Breed.Remove(breed);

                await _db.SaveChangesAsync();

            }

            return Json("success");

        }
        [HttpPost]
        public async Task<IActionResult> _Index(SearchBreed search)
        {
            List<BreedViewModel> model = (from item in _db.Breed
                                             //join ur in _context.UserRoles on item.Id equals ur.UserId
                                         where
                                         ( (item.Name == search.Name || search.Name == null) &&
                                         (item.Type == search.Type || search.Type == null))
                                         select new BreedViewModel
                                         {
                                             Id = AesCrypto.Enkrypt(item.Id),
                                             Name = item.Name,
                                             Type = item.Type,
                                             
                                         }).ToList();

           

            return Json(model);
        }

        [HttpPost]
        public async Task<JsonResult> OpenIndexReport()
        {
            var breed = _db.Breed.ToList();
            var query = breed
               .Select(q => new BreedReportModel
               {
                   Id = q.Id,
                   Name = q.Name,
                   Type = q.Type
               }).ToList();


            HttpContext.Session.SetString("Path", "Reports\\BreedReport.rdl");
            HttpContext.Session.Set("queryresult", query);


            return Json(true);
        }
    }

  
}

CattleMgm/Views/Breed/Create.cshtml
@model BreedCreateViewModel

@{
    ViewData["Title"] = "Regjistrimi i llojit te gjedheve";
}

<div class="card">
    <div class="card-header with-border">
        <h4>Plotesoni te dhenat me poshte</h4>
    </div>
    <form asp-action="Create" asp-controller="Breed" method="post">
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <label class="required" asp-for="Name">Emri i Llojit</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="Type">Tipi i Llojit</label>
                    <input asp-for="Type" class="form-control" />
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <input type="submit" class="btn btn-sm btn-primary" value="Regjistro" />
        </div>
    </form>
</div>

<style>
    .validation-summary-errors{
        color: red;
    }
</style>

CattleMgm/Views/Breed/Edit.cshtml
@model BreedEditViewModel

@{
    ViewData["Title"] = "Editimi i llojit te gjedheve";
}
<div class="card">
    <div class="modal-header">
        <h5 class="modal-title">Editimi i llojit te gjedhes</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
    <form asp-action="Edit" asp-controller="Breed" class="noLoading" id="frmEditBreed" method="post" data-ajax="true" data-ajax-method="post" data-ajax-success="EditSuccess" role="form">
        <div class="card-body">
            @Html.AntiForgeryToken()
            <input asp-for="Id" hidden />
            <div class="row">
                <div class="col-md-6">
                    <label  class="required" asp-for="Name">Emri i Gjedhes</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="Type">Tipi </label>
                    <input asp-for="Type" class="form-control" />
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>


            </div>
        </div>
        <div class="card-footer">
            <input type="submit" class="btn btn-sm btn-primary" value="Edito" />
        </div>
    </form>

</div>
<script type="text/javascript">
    var form = $('#frmEditBreed');
    form.removeData('validator');
    form.removeData('unobtrusiveValidation');
    $.validator.unobtrusive.parse(form);


    function EditSuccess(data) {
        console.log(data);
        if (data.errorNumber == ErrorNumber.SUCCESS) {
            Swal.fire({
                icon: 'success',
                title: data.title,
                text: data.errorDescription,
                confirmButtonText: "Okay"
            }).then(t => {
                window.location.reload()
            })
        } else if (data.errorNumber == ErrorNumber.WARNING) {
            Swal.fire({
                icon: 'warning',
                title: data.title,
                text: data.ErrorDescription,
                confirmButtonText: "Okay"
            })
        }
    }
</script>

CattleMgm/Views/Breed/Index.cshtml
@model CattleMgm.Models.SearchBreed

@*@model List<BreedViewModel>

*@@{
    ViewData["Title"] = "Lista e llojit te gjedheve";
}
<div class="card">
    <div class="card-header">
        <div class="card-toolbar float-end">
            <a class="btn btn-sm btn-primary" asp-action="Create" asp-controller="Breed">Regjistro</a>
        </div>
    </div>
    <div class="card-body">
        <form asp-action="_Index" asp-controller="Breed" method="post" data-ajax="true" data-ajax-success="kt_ajax_success" data-ajax-method="POST" id="frmSearch">
            @Html.AntiForgeryToken()
            @Html.Hidden("type")

            <div class="row">
                <div class="col-md-2">
                    <div class="mb-3">
                        <label asp-for="Name" class="form-label mb-lg-0"></label>
                        <input asp-for="Name" type="text" class="form-control" />
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="mb-3">
                        <label asp-for="Type" class="form-label mb-lg-0"></label>
                        <input asp-for="Type" type="text" class="form-control" />
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="mb-3">
                        <label asp-for="Name" style="visibility:hidden"></label><br />
                        <button type="submit" name="button" class="btn btn-primary">Kerko</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
    <div class="card-body">
        <div class="button-items" style="float:right;">
            <div class="btn-group dropstart">
                <button style="margin:0 5px 7px 0" type="button" class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="mdi mdi-chevron-left"></i>Shkarko
                </button>
                <div class="dropdown-menu">
                    <button class="dropdown-item" onclick="Report(ReportType.PDF)">
                        <img src="~/Media/Extensions/pdf.png" class="btn-download" asp-append-version="true" />
                        <span class="title text-center w-100">PDF</span>
                    </button>
                    <button class="dropdown-item" onclick="Report(ReportType.EXCEL)">
                        <img src="~/Media/Extensions/xls.png" class="btn-download" asp-append-version="true" />
                        <span class="title text-center w-100">Excel</span>
                    </button>
                </div>
            </div>
        </div>

        <table id="tblResult" class="table table-responsive">
            <thead>
                <tr>
                    <th>*</th>
                    <th>Emri i llojit</th>
                    <th>Tipi i llojit</th>
                    <th>Veprimet</th>
                </tr>
            </thead>
            <tbody>
            @*    @foreach (var breed in Model)
                {
                    <tr>
                        <td>@breed.Name</td>
                        <td>@breed.Type</td>
                        <td class="button-td">
                            <div class="d-flex">
                            <a class="btn btn-sm btn-primary me-2" onclick="EditBreed('@AesCrypto.Enkrypt(breed.Id)')"><i class="fa fa-edit"></i>Edit</a>
                            <a class="btn btn-sm btn-danger" onclick="deleteBreed(event,'@breed.Id')">Delete</a>
                                </div>
                        </td>
                    </tr>
                }*@
            </tbody>
        </table>
</div>
@section Scripts{
    <script type="text/javascript">
        $("#breed-table").DataTable({
            keys: true,
            responsive: true,
            pageLength: 10,
            "ordering": false

        });
    

 function CreateBreed() {
            $('#modal-center-large').find('.modal-content').load('@Url.Action("Create", "Breed")', function() {
                $('#modal-center-large').modal('toggle')
            })
        }

        function EditBreed(id) {

            $('#modal-center-large').find('.modal-content').load('@Url.Action("Edit", "Breed")?ide=' + id, function() {
                $('#modal-center-large').modal('toggle')
            })

        }


            function DeleteBreed(id) {
                Swal.fire({
                    title: 'A jeni te sigurt?',
                    text: "Kjo ben fshirjen e llojit!",
                    icon: 'warning',
                    showCancelButton: true,
                    cancelButtonText: 'Jo, kthehu.',
                    buttonsStyling: false,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Po, deshiroj ta fshij!',
                    customClass: {
                        confirmButton: "btn btn-primary",
                        cancelButton: "btn btn-secondary"
                    }
                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            url: '@Url.Action("Delete", "Breed")',
                            type: 'POST',
                            data: { id: id },
                            success: function (data) {
                                Swal.fire({
                                    text: "Lloji u fshi me sukses!",
                                    icon: "success",
                                    buttonsStyling: false,
                                    confirmButtonText: "Ne rregull!",
                                    customClass: {
                                        confirmButton: "btn btn-primary"
                                    }
                                }).then(function (result) {
                                    location.href = location.href;
                                });
                            },
                            error: function (xhr, status, error) {
                                console.log(xhr.responseText); // Log the full error response
                                Swal.fire({
                                    text: "Sorry, there was an error deleting the cattle. Please try again later.",
                                    icon: "error",
                                    buttonsStyling: false,
                                    confirmButtonText: "Ok, got it!",
                                    customClass: {
                                        confirmButton: "btn btn-primary"
                                    }
                                });
                            }
                        });
                    }
                });
            }

            function Report(type) {
                if (type == '@((int)ReportType.PDF)' || type == '@((int)ReportType.Excel)') {
                    $.ajax({
                        url: "/Breed/OpenIndexReport",
                        cache: false,
                        type: "POST",
                        dataType: "json",
                        success: function () {
                            if (type == '@((int)ReportType.Excel)')
                                window.open("/Reports/Design/?format=excel", '_blank');
                            else {
                                let W = window.open("/Reports/Design/?format=pdf", '_blank');
                                W.onload = function () { this.document.title = 'Raporti'; }
                            }
                        }
                    });
                }
            }
           
           
        function kt_ajax_success(data) {
            var rowno = 0;
            $('#tblResult').DataTable({
                "destroy": true,
                keys: true,
                responsive: true,
                pageLength: 10,
                data: data,
                columns: [
                    {
                        'data': function (row,type, set) {
                            rowno++;
                            return rowno;
                        }
                    },
                    { "data": "name" },
                    { "data": "type" },
                       
                   
                    {
                        "data": function (row, type, set) {
                            let currentDate = new Date();
                            var lockDate = new Date(row.LockoutEnd);
                            var dropdown = '<div class="button-items table-button-items" style="float:right;">' +
                                '<div class="btn-group dropstart">' +
                                '<button type="button" class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">' +
                                '<i class="mdi mdi-chevron-left"></i>' + 'Veprimet' +
                                '</button>' +

                                '<div class="dropdown-menu">' +
                                '<button class="dropdown-item" type="button" onclick="EditBreed(\'' + row.id + '\')">' +
                                '<span class="title" style=" margin-top: 3px; margin-left: 10px;">Edit</span>' +
                                '</button>';
                            dropdown += '<button class="dropdown-item" type="button" onclick="DeleteBreed(\'' + row.id + '\')">' +
                                ' <span class="title" style=" margin-top: 3px; margin-left: 10px;">Delete</span>' +
                                '</button>' +
                                '</div>' +
                                '</div>' +
                                '</div>';

                            return dropdown;
                        }
                    }
                ],
                initComplete: function () {
                    $('.table-button-items').parent().addClass('button-td');
                }
            })
        }
    </script>
    
}