CattleMgm/ViewModels/Log/LogViewModel.cs
namespace CattleMgm.ViewModels.Log
{
    public class LogViewModel
    {
        public int Id { get; set; }

        public string UserId { get; set; }

        public string Controller { get; set; }

        public string Action { get; set; }

        public string HttpMethod { get; set; }

        public DateTime Date { get; set; }

        public string Url { get; set; }

    }

    public class LogDetailsViewModel
    {
        public int Id { get; set; }

        public string UserId { get; set; }

        public string Controller { get; set; }

        public string Action { get; set; }

        public string HttpMethod { get; set; }

        public string Url { get; set; }

        public string Exception { get; set; }

    }

    public class SearchLogs
    {

        public string? UserId { get; set; }

        public string? Controller { get; set; }

        public string? DateMeasured { get; set; }
    }
}

CattleMgm/Controllers/LogController.cs
using CattleMgm.Data.Entities;
using CattleMgm.Data;
using CattleMgm.Models;
using CattleMgm.Repository.Cattles;
using CattleMgm.Repository.Farm;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using CattleMgm.Helpers;
using CattleMgm.ViewModels.Cattle;
using CattleMgm.Repository.Log;
using CattleMgm.ViewModels.Log;
using CattleMgm.ViewModels.CattleTemperature;
using CattleMgm.ViewModels.Humidity;
using CattleMgm.ViewModels.Position;
using Microsoft.EntityFrameworkCore;
using CattleMgm.Helpers.Security;
using CattleMgm.ViewModels.User;

namespace CattleMgm.Controllers
{
    public class LogController : BaseController
    {
        private ILogRepository _logRepository;
        public LogController(ApplicationDbContext context, praktikadbContext db,
            UserManager<ApplicationUser> userManager,
                                ILogRepository logRepository) : base(context, db, userManager)
        {
            _logRepository = logRepository;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Lista e erroreve";

            //var lista = _logRepository.GetLogs();

            //List<LogViewModel> listaViewModel = new List<LogViewModel>();

            //foreach (var log in lista)
            //{
            //    listaViewModel.Add(new LogViewModel
            //    {
            //        Id = (int)log.LogId,
            //        UserId = log.UserId,
            //        Controller = log.Controller,
            //        Action = log.Action,
            //        HttpMethod = log.HttpMethod,
            //        Date=log.InsertedDate.ToShortDateString(),
            //        Url = log.Url
            //    });
            //}

            //listaViewModel = listaViewModel.OrderByDescending(q => q.Id).ToList();

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var log = await _db.Log.Where(q => q.LogId == id).FirstOrDefaultAsync();



            if (log == null)
            {
                return NotFound();
            }

            int index = log.Url.LastIndexOf('/');
            int index1 = log.Exception.IndexOf(',')-1;
            LogDetailsViewModel model = new LogDetailsViewModel();

            model.Id = (int)log.LogId;
            model.UserId = log.UserId;
            model.Controller = log.Controller;
            model.Action = log.Action;
            model.HttpMethod = log.HttpMethod;
            model.Url = log.Url.Substring(0,index);
            model.Exception = log.Exception.Substring(1,index1);


            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> _Index(SearchLogs search)
        {
            DateTime dp;

            List<LogViewModel> model = (from item in _db.Log
                                         where
                                         ((item.UserId == search.UserId || search.UserId == null) &&
                                         (item.Controller == search.Controller || search.Controller == null))
                                         select new LogViewModel
                                         {
                                             Id = (int)item.LogId,
                                             UserId = item.UserId,
                                             Controller = item.Controller,
                                             Action=item.Action,
                                             HttpMethod=item.HttpMethod,
                                             Date=item.InsertedDate
                                         }).ToList();

            if (search.DateMeasured != null)
            {
                dp = DateTime.Parse(search.DateMeasured).Date;

                model = model.Where(q => q.Date.Date == dp).ToList();
            }

            return Json(model);
        }
    }
}

CattleMgm/Views/Log/Details.cshtml
@model LogDetailsViewModel
@{
}

<div class="modal-header">
    <h5 class="modal-title">Detajet e erroreve</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <table id="log-table1" class="table table-responsive">
        <thead>
            <tr>
                <th>User</th>
                <th>Url</th>
                <th>Exception</th>
            </tr>
        </thead>
        <tbody>
                <tr>
                    <td>@Model.UserId</td>
                    <td>@Model.Url</td>
                    <td>@Model.Exception</td>
                </tr>
        </tbody>
    </table>
    <div class="modal-footer modal-footer-uniform w-full justify-content-between">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Mbyll</button>
    </div>

</div>


<script type="text/javascript">
    var form = $('#log-table1');
    form.removeData('validator');
    form.removeData('unobtrusiveValidation');
    $.validator.unobtrusive.parse(form);
</script>

CattleMgm/Views/Log/Index.cshtml
@model SearchLogs
@{
    ViewData["Title"] = "Lista e erroreve";
}

<div class="card">
    <div class="card-header with-border">
        <h4>Plotesoni te dhenat me poshte per filtrim te tabeles</h4>
    </div>
    <div class="card-body">
        @*<div class="row">
            <div class="col-md-3">
                <label for="UserId">User id:</label>
                <input type="text" id="UserId" />
            </div>
            <div class="col-md-3">
                <label for="Controller">Controller:</label>
                <input type="text" id="Controller" />
            </div>
            <div class="col-md-3">
                <label for="Action">Action:</label>
                <input type="text" id="Action" />
            </div>
            <div class="col-md-3">
                <label for="Date">Inserted Date:</label>
                <input type="text" id="Date" />
            </div>
        </div>*@
        <form asp-action="_Index" asp-controller="Log" method="post" data-ajax="true" data-ajax-success="kt_ajax_success" data-ajax-method="POST" id="frmSearch">
            @Html.AntiForgeryToken()
            @Html.Hidden("type")
            <div class="row">
                <div class="col-md-2">
                    <div class="mb-3">
                        <label asp-for="UserId" class="form-label mb-lg-0"></label>
                        <input asp-for="UserId" type="text" class="form-control" />
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="mb-3">
                        <label asp-for="Controller" class="form-label mb-lg-0"></label>
                        <input asp-for="Controller" type="text" class="form-control" />
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="mb-3">
                        <label asp-for="DateMeasured" class="form-label mb-lg-0"></label>
                        <input asp-for="DateMeasured" class="form-control" type="date" />
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="mb-3">
                        <label asp-for="UserId" style="visibility:hidden"></label><br />
                        <button type="submit" name="button" class="btn btn-primary">Kerko</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <table class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;" id="log-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>User</th>
                    <th>Controller</th>
                    <th>Action</th>
                    <th>Http Method</th>
                    <th>Inserted Date</th>
                    <th data-priority="1">Veprimet</th>
                </tr>
            </thead>
            <tbody>
                @*@foreach (var item in Model)
                {
                    <tr>
                        <td>@item.UserId</td>
                        <td>@item.Controller</td>
                        <td>@item.Action</td>
                        <td>@item.HttpMethod</td>
                        <td>@item.Date</td>
                        <td>
                            <a class="btn btn-sm btn-primary" onclick="EditMenu(@item.Id)"><i class="fa fa-info-circle"></i> Details</a>
                        </td>
                        
                    </tr>
                }*@
            </tbody>
        </table>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $("#log-table").DataTable({
            keys: true,
            responsive: true,
            pageLength: 10,
            "ordering": false

        });

        function EditMenu(id) {

            $('#modal-center-large').find('.modal-content').load('@Url.Action("Details", "Log")?id=' + id, function () {
                $('#modal-center-large').modal('toggle')
            })
        }

        //$(document).ready(function () {
        //    $("#UserId, #Date, #Controller, #Action").on('input', function () {

        //        var user = $("#UserId").val().toLowerCase();
        //        var date = $("#Date").val().toLowerCase();
        //        var con = $("#Controller").val().toLowerCase();
        //        var action = $("#Action").val().toLowerCase();

        //        $("#log-table tbody tr").filter(function () {

        //            var rowUser = $(this).find("td:eq(0)").text().toLowerCase();
        //            var rowDate = $(this).find("td:eq(4)").text().toLowerCase();
        //            var rowCon = $(this).find("td:eq(1)").text().toLowerCase();
        //            var rowAction = $(this).find("td:eq(2)").text().toLowerCase();

        //            return (rowUser.indexOf(user) === -1 || rowDate.indexOf(date) === -1 || rowCon.indexOf(con) === -1 || rowAction.indexOf(action) === -1);

        //        }).hide();

        //        $("#log-table tbody tr").filter(function () {

        //            var rowUser = $(this).find("td:eq(0)").text().toLowerCase();
        //            var rowDate = $(this).find("td:eq(4)").text().toLowerCase();
        //            var rowCon = $(this).find("td:eq(1)").text().toLowerCase();
        //            var rowAction = $(this).find("td:eq(2)").text().toLowerCase();

        //            return (rowUser.indexOf(user) !== -1 && rowDate.indexOf(date) !== -1 && rowCon.indexOf(con) !== -1 && rowAction.indexOf(action) !== -1);

        //        }).show();
        //    });
        //});

        function kt_ajax_success(data) {
            var rowno = 0;
            $('#log-table').DataTable({
                "destroy": true,
                keys: true,
                responsive: true,
                pageLength: 10,
                data: data,
                columns: [
                    {
                        'data': function (row, type, set) {
                            rowno++;
                            return rowno;
                        }
                    },
                    { "data": "userId" },
                    { "data": "controller" },
                    { "data": "action" },
                    { "data": "httpMethod" },
                    { "data": "date" },
                    {
                        "data": function (row, type, set) {
                            let currentDate = new Date();
                            var lockDate = new Date(row.LockoutEnd);
                            var dropdown = '<div class="button-items table-button-items" style="float:right;">' +
                                '<div class="btn-group dropstart">' +
                                '<button type="button" class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">' +
                                '<i class="mdi mdi-chevron-left"></i>' + 'Veprimet' +
                                '</button>' +

                                '<div class="dropdown-menu">' +
                                '<button class="dropdown-item" type="button" onclick="EditMenu(\'' + row.id + '\')">' +
                                '<span class="title" style=" margin-top: 3px; margin-left: 10px;">Details</span>' +
                                '</button>';
                            dropdown += 
                                '</div>' +
                                '</div>' +
                                '</div>';

                            return dropdown;
                        }
                    }
                ],
                initComplete: function () {
                    $('.table-button-items').parent().addClass('button-td');
                }
            })
        }
    </script>
}