CattleMgm/ViewModels/Position/PositionViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CattleMgm.ViewModels.Position
{
    public class PositionViewModel
    {
        public int Id { get; set; }

        public string CattleName { get; set; }

        public double Lat { get; set; }

        public double Long { get; set; }
        public DateTime DateMeasured { get; set; }
        
    }

    public class PositionCreateViewModel
    {
        [Required(ErrorMessage = "Ju lutem zgjedhni gjedhen")]
        [Display(Name = "Emri i Gjedhes")]
        public int CattleId { get; set; }

        [Required(ErrorMessage = "Kjo fushe eshte obligative")]
        [Display(Name = "Latitude")]
        public double Lat { get; set; }

        [Required(ErrorMessage = "Kjo fushe eshte obligative")]
        [Display(Name = "Longitude")]
        public double Long { get; set; }

    }

    public class PositionEditViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Kjo fushë eshte obligative")]
        [Display(Name = "Id")]
        public string CattleId { get; set; }

        [Required(ErrorMessage = "Kjo fushë eshte obligative")]
        [Display(Name = "Latitude")]
        public double Lat { get; set; }

        [Required(ErrorMessage = "Kjo fushë eshte obligative")]
        [Display(Name = "Longitude")]
        public double Long { get; set; }
    }

    public class PositionReportModel
    {
        public string Id { get; set; }

        public string CattleName { get; set; }

        public double Lat { get; set; }

        public double Long { get; set; }

    }
    public class SearchPosition
    {
        [Display(Name = "Emri i gjedhes")]
        public int? CattleId { get; set; }
        [Display(Name = "Latitude")]
        public double? Lat { get; set; }
        [Display(Name = "Longitude")]
        public double? Long { get; set; }
        [Display(Name = "Data e matjes")]
        public string? DateMeasured { get; set; }
    }
}

CattleMgm/Controllers/PositionController.cs
using CattleMgm.Data;
using CattleMgm.Data.Entities;
using CattleMgm.Helpers.Security;
using CattleMgm.Models;
using CattleMgm.Models.Session;
using CattleMgm.Repository.Farm;
using CattleMgm.Repository.Position;
using CattleMgm.ViewModels;
using CattleMgm.ViewModels.Farm;
using CattleMgm.ViewModels.Menu;
using CattleMgm.ViewModels.Position;
using CattleMgm.ViewModels.User;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CattleMgm.Controllers
{
    public class PositionController : BaseController
    {
        public IPositionRepository _posRepository;
        public PositionController(ApplicationDbContext context,
            praktikadbContext db,
            UserManager<ApplicationUser> userManager,
            IPositionRepository posRepository) : base(context, db, userManager)
        {
            _posRepository = posRepository;
        }

        public async Task<IActionResult> Index()
        {
            var positions = await _db.Cattle.Select(q => new { q.Id, FullName = q.Name })
                                .ToListAsync();
            ViewBag.Cattles = new SelectList(positions, "Id", "FullName");
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var positions = await _db.Cattle.Select(q => new { q.Id, FullName = q.Name })
                                .ToListAsync();
            ViewBag.Cattles = new SelectList(positions, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(PositionCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Ka ndodhur nje gabim. Plotesoni te dhenat obligative");
                return View(model);
            }
            
            CattlePosition pos = new CattlePosition();
            pos.CattleId = model.CattleId;
            pos.Lat = model.Lat;
            pos.Long = model.Long;
            pos.DateMeasured = DateTime.Now;
            pos.CreatedBy = user.Id;

            await _db.CattlePosition.AddAsync(pos);

            await _db.SaveChangesAsync();

            return RedirectToAction("Index");

        }

        //estrdyuiojhgfgghvjbj

        [HttpGet]
        public IActionResult Edit(int? id)
        {

            if (id == null)
            {
                return BadRequest();
            }

            //int did = AesCrypto.Decrypt<int>(ide);

            var pos = _db.CattlePosition.Find(id);

            if (pos == null)
            {
                return NotFound();
            }

            PositionEditViewModel editViewModel = new PositionEditViewModel
            {
                CattleId = pos.CattleId.ToString(),
                Lat = pos.Lat,
                Long = pos.Long
            };

            return PartialView(editViewModel);
        }

        [HttpPost]
        public IActionResult Edit(PositionEditViewModel model)
        {

            ErrorViewModel error = new ErrorViewModel { ErrorNumber = Helpers.ErrorStatus.Success, ErrorDescription = "Menu eshte modifikuar me sukses", Title = "Sukses" };

            if (!ModelState.IsValid)
            {
                error = new ErrorViewModel { ErrorNumber = Helpers.ErrorStatus.Warning, ErrorDescription = "Plotesoni te dhenat obligative", Title = "Lajmerim" };
                return Json(error);
            }

            var pos = _db.CattlePosition.Find(model.Id);

            if (pos == null)
            {
                return NotFound();
            }

            pos.Id = model.Id;
            pos.Lat = model.Lat;
            pos.Long = model.Long;

            _db.Update(pos);

            _db.SaveChanges();

            return Json(error);
        }

        [HttpPost]
        public async Task<JsonResult> OpenIndexReport()
        {
            var positions = new List<CattlePosition>();
            positions = await _posRepository.GetAllPositions();
            var query = positions
               .Select(q => new PositionReportModel
               {
                   Id = q.Id.ToString(),
                   CattleName = $"{q.Cattle.Name}",
                   Lat = q.Lat,
                   Long = q.Long
               }).ToList();


            HttpContext.Session.SetString("Path", "Reports\\positionReport.rdl");
            HttpContext.Session.Set("queryresult", query);


            return Json(true);
        }

        [HttpPost]
        public async Task<IActionResult> _Index(SearchPosition search)
        {
            DateTime dp;


            List<PositionViewModel> model = (from item in _db.CattlePosition.Include(x => x.Cattle)
                                                 //join ur in _context.UserRoles on item.Id equals ur.UserId
                                             where
                                         (item.CattleId==search.CattleId|| search.CattleId == null)&&
                                         (item.Lat==search.Lat||search.Lat==null)&&
                                         (item.Long == search.Long || search.Long == null) 
                                         

                                         select new PositionViewModel
                                         {
                                             Id =item.Id,
                                             CattleName = item.Cattle.Name,
                                             Lat = item.Lat,
                                             Long = item.Long,
                                             DateMeasured = item.DateMeasured
                                         }).ToList();

            if (search.DateMeasured != null)
            {
                dp = DateTime.Parse(search.DateMeasured).Date;

                model = model.Where(q => q.DateMeasured.Date == dp).ToList();
            }

            return Json(model);
        }
    }
}

CattleMgm/Views/Position/Create.cshtml
@model PositionCreateViewModel
@{
    ViewData["Title"] = "Regjistrimi i pozicionit";
}

<div class="card">
    <div class="card-header with-border">
        <h4>Plotesoni te dhenat me poshte</h4>
    </div>
    <form id="createForm" method="post">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <label class="required" asp-for="CattleId"></label>
                    @Html.DropDownListFor(m=>m.CattleId, ViewBag.Cattles as SelectList, "Zgjedh", new { @class = "form-control select2"})
                    @*ekuivalente me dropdownlistfor*@
                    @* <select asp-for="RoleId" asp-items="ViewBag.Roles" class="form-control select2">
                    <option></option>
                    </select>*@
                    <span asp-validation-for="CattleId" class="text-danger"></span>
                </div>
                <div class="col-md-3">
                    <label class="required" asp-for="Lat"></label>
                    <input asp-for="Lat" class="form-control" />
                    <span asp-validation-for="Lat" class="text-danger"></span>
                </div>
                <div class="col-md-3">
                    <label class="required" asp-for="Long"></label>
                    <input asp-for="Long" class="form-control" />
                    <span asp-validation-for="Long" class="text-danger"></span>
                </div>

            </div>
        </div>
        <div class="card-footer">
            <input type="submit" class="btn btn-sm btn-primary" value="Regjistro" />
        </div>
    </form>

</div>

CattleMgm/Views/Position/Edit.cshtml
@model PositionEditViewModel
@{
}

<div class="modal-header">
    <h5 class="modal-title">Editimi i pozicionit</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <form asp-action="Edit" asp-controller="Position" class="noLoading" id="frmEditPosition" method="post" data-ajax="true" data-ajax-method="post" data-ajax-success="EditSuccess" role="form">

        @Html.AntiForgeryToken()
        <input asp-for="Id" hidden />
        <div class="row form-group">
            <div class="col-md-4">
                <label asp-for="CattleId" class="required form-label"></label>
                <input asp-for="CattleId" class="form-control" readonly/>
                <span asp-validation-for="CattleId" class="text-danger" />
            </div>
            <div class="col-md-4">
                <label asp-for="Lat" class="required form-label"></label>
                <input asp-for="Lat" class="form-control" />
                <span asp-validation-for="Lat" class="text-danger" />
            </div>
            <div class="col-md-4">
                <label asp-for="Long" class="required form-label"></label>
                <input asp-for="Long" class="form-control" />
                <span asp-validation-for="Long" class="text-danger" />
            </div>
        </div>
        <div class="modal-footer modal-footer-uniform w-full justify-content-between">
            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Mbyll</button>
            <button type="submit" class="btn btn-outline-primary">Ndrysho</button>
        </div>
    </form>

    
</div>


<script type="text/javascript">
    var form = $('#frmEditPosition');
    form.removeData('validator');
    form.removeData('unobtrusiveValidation');
    $.validator.unobtrusive.parse(form);

    function EditSuccess(data) {
        console.log(data);

        if (data.errorNumber == ErrorNumber.SUCCESS) {
            Swal.fire({
                icon: 'success',
                title: data.title,
                text: 'Rekordi u ndryshua me sukses',
                confirmButtonText: "Okay"
            }).then(t => {
                window.location.reload()
            })
        } else if (data.errorNumber == ErrorNumber.WARNING) {
            Swal.fire({
                icon: 'warning',
                title: data.title,
                text: data.ErrorDescription,
                confirmButtonText: "Okay"
            })
        }
    }
</script>

CattleMgm/Views/Position/Index.cshtml
@model SearchPosition
@{
    ViewData["Title"] = "Lista e pozicioneve";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Leaflet Tutorial</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />

    <style>
        #map {
            height: 100vh;
            width: 100%;
        }
    </style>
</head>
<body>
    <div class="card">
        <div class="card-header">
            <div class="card-toolbar float-end">
                <a class="btn btn-sm btn-primary" asp-action="Create" asp-controller="Position">Regjistro</a>
            </div>
        </div>
        <div class="card-body">
            <form asp-action="_Index" asp-controller="Position" method="post" data-ajax="true" data-ajax-success="kt_ajax_success" data-ajax-method="POST" id="frmSearch">
                @Html.AntiForgeryToken()
                @Html.Hidden("type")
                <div class="row">
                    <div class="col-md-2">
                        <div class="mb-3">
                            <label asp-for="CattleId" class="form-label mb-lg-0"></label>
                            @Html.DropDownListFor(m=>m.CattleId, ViewBag.Cattles as SelectList, "Zgjedh", new { @class = "form-control select2"} )
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="mb-3">
                            <label asp-for="Lat" class="form-label mb-lg-0"></label>
                            <input asp-for="Lat" type="text" class="form-control" />
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="mb-3">
                            <label asp-for="Long" class="form-label mb-lg-0"></label>
                            <input asp-for="Long" type="text" class="form-control" />
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="mb-3">
                            <label asp-for="DateMeasured" class="form-label mb-lg-0"></label>
                            <input asp-for="DateMeasured" class="form-control" type="date" />
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="mb-3">
                            <label asp-for="Lat" style="visibility:hidden"></label><br />
                            <button type="submit" name="button" class="btn btn-primary">Kerko</button>
                        </div>
                    </div>
                </div>
            </form>
            <div class="button-items" style="float:right;">
                <div class="btn-group dropstart">
                    <button style="margin:0 5px 7px 0" type="button" class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="mdi mdi-chevron-left"></i>Shkarko
                    </button>
                    <div class="dropdown-menu">
                        <button class="dropdown-item" onclick="Report(ReportType.PDF)">
                            <img src="~/Media/Extensions/pdf.png" class="btn-download" asp-append-version="true" />
                            <span class="title text-center w-100">PDF</span>
                        </button>
                        <button class="dropdown-item" onclick="Report(ReportType.EXCEL)">
                            <img src="~/Media/Extensions/xls.png" class="btn-download" asp-append-version="true" />
                            <span class="title text-center w-100">Excel</span>
                        </button>
                    </div>
                </div>
            </div>
            <table class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;" id="position-table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Emri i Gjedhes</th>
                        <th id="lat">Latitude</th>
                        <th id="long">Longitude</th>
                        <th>Data e matjes</th>
                        <th data-priority="1">Veprimet</th>
                    </tr>
                </thead>
                <tbody>
                   @* @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.CattleName</td>
                            <td>@item.Lat</td>
                            <td>@item.Long</td>
                            <td>@item.DateMeasured</td>
                            <td>
                                <a class="btn btn-sm btn-primary" onclick="EditMenu(@item.Id)"><i class="fa fa-edit"></i> Edit</a>

                                <a class="btn btn-sm btn-primary" onclick="EditMap(@item.Lat,@item.Long)"><i class="fa fa-map-marked-alt"></i> Map</a>
                            </td>
                        </tr>
                    }*@
                </tbody>
            </table>
        </div>
    </div>
    <div id="map"></div>
</body>
</html>

@section Scripts{
    <script type="text/javascript">
        $("#position-table").DataTable({
            keys: true,
            responsive: true,
            pageLength: 10,
            "ordering": false
        });

        function EditMap(lat,long) {
            
            var map = L.map('map').setView([lat, long], 12);

            var singleMarker = L.marker([lat, long]);
            singleMarker.addTo(map);
            var popup = singleMarker.bindPopup('Pozicioni i gjedhes se zgjedhur');
            popup.addTo(map);

            // Google Map Layer

            googleStreets = L.tileLayer('http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}', {
                maxZoom: 20,
                subdomains: ['mt0', 'mt1', 'mt2', 'mt3']
            });
            googleStreets.addTo(map);

            map.once("click",function(){
                Swal.fire(
                    'Informacion',
                    'Shtypni ENTER per shfaqjen e pozicionit te gjedhes tjeter te zgjedhur',
                    'OK'
                )
            });

            document.addEventListener("keypress",function(){
                if (event.key === "Enter") {
                    location.reload();
                }
            });
        }

        function Report(type) {
            if (type == '@((int)ReportType.PDF)' || type == '@((int)ReportType.Excel)') {
                $.ajax({
                    url: "/Position/OpenIndexReport",
                    cache: false,
                    type: "POST",
                    dataType: "json",
                    success: function () {
                        if (type == '@((int)ReportType.Excel)')
                            window.open("/Reports/Design/?format=excel", '_blank');
                        else {
                            let W = window.open("/Reports/Design/?format=pdf", '_blank');
                            W.onload = function () { this.document.title = 'Raporti'; }
                        }
                    }
                });
            }
        }
        function EditPosition(ide) {
            $('#modal-center-large').find('.modal-content').load('@Url.Action("Edit", "Position")?id=' + ide, function () {
                $('#modal-center-large').modal('toggle')
            })
        }


        function kt_ajax_success(data) {
            var rowno = 0;
            $('#position-table').DataTable({
                "destroy": true,
                keys: true,
                responsive: true,
                pageLength: 10,
                data: data,
                columns: [
                    {
                        'data': function (row, type, set) {
                            rowno++;
                            return rowno;
                        }
                    },
                    { "data": "cattleName" },
                    { "data": "lat" },
                    { "data": "long" },
                    { "data": "dateMeasured" },
                    {
                        "data": function (row, type, set) {
                            let currentDate = new Date();
                            var lockDate = new Date(row.LockoutEnd);
                            var dropdown = '<div class="button-items table-button-items" style="float:right;">' +
                                '<div class="btn-group dropstart">' +
                                '<button type="button" class="btn btn-sm btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">' +
                                '<i class="mdi mdi-chevron-left"></i>' + 'Veprimet' +
                                '</button>' +

                                '<div class="dropdown-menu">' +
                                '<button class="dropdown-item" type="button" onclick="EditPosition(\'' + row.id + '\')">' +
                                '<span class="title" style=" margin-top: 3px; margin-left: 10px;">Edit</span>' +
                                '</button>';
                            dropdown += '<button class="dropdown-item" type="button" onclick="EditMap(\'' + row.lat + "\',\'" + row.long + '\')">' +
                                ' <span class="title" style=" margin-top: 3px; margin-left: 10px;">Map</span>' +
                                '</button>' +
                                '</div>' +
                                '</div>' +
                                '</div>';

                            return dropdown;
                        }
                    }
                ],
                initComplete: function () {
                    $('.table-button-items').parent().addClass('button-td');
                }
            })}

    </script>
}